// ReSharper disable InconsistentNaming
namespace HabBridge.Server.Habbo
{
    public enum Incoming
    {
        Unknown = 0,
        LandingLoadWidget,
        LandingRefreshPromos,
        LandingRefreshReward,
        SendBadgeCampaign,
        LandingCommunityGoal,
        HotelViewCountdown,
        HotelViewDailyquest,
        HotelViewRequestBadge,
        GetHotelViewHallOfFame,
        GetCurrencyBalance,
        GetSubscriptionData,
        OnlineConfirmation,
        UserGetVolumeSettings,
        SaveClientSettings,
        GetTalentsTrack,
        LoadUserProfile,
        SetRelationship,
        GetUserTags,
        OnDisconnect,
        GoToHotelView,
        UserUpdateLook,
        UserUpdateMotto,
        CheckUsername,
        ChangeUsername,
        Wardrobe,
        WardrobeUpdate,
        NavigatorGetEvents,
        NavigatorGetFavouriteRooms,
        NavigatorGetFeaturedRooms,
        NavigatorGetFriendsRooms,
        NavigatorGetHighRatedRooms,
        NavigatorGetMyRooms,
        NavigatorGetPopularRooms,
        NavigatorGetPopularTags,
        NavigatorGetRecentRooms,
        NavigatorSearchRoomByName,
        NavigatorGetRecommendedRooms,
        NavigatorGetFlatCategories,
        NavigatorGetPopularGroups,
        NavigatorGetRoomsWithFriends,
        NewNavigator,
        SearchNewNavigatorEvent,
        NewNavigatorAddSavedSearchEvent,
        NewNavigatorDeleteSavedSearchEvent,
        NewNavigatorResizeEvent,
        NewNavigatorCollapseCategoryEvent,
        NewNavigatorUncollapseCategoryEvent,
        CanCreateRoom,
        CreateRoom,
        GoToRoomByName,
        ToggleStaffPick,
        GetCatalogClubPage,
        GetCatalogOffer,
        CatalogueOfferConfig,
        GetSellablePetBreeds,
        ReloadRecycler,
        GetGiftWrappingConfiguration,
        GetRecyclerRewards,
        CatalogPromotionGetRooms,
        GetCatalogClubGifts,
        ChooseClubGift,
        PromoteRoom,
        RetrieveSongID,
        CheckPetname,
        EcotronRecycle,
        RedeemVoucher,
        BuildersClubUpdateFurniCount,
        PlaceBuildersFurniture,
        PurchaseTargetedOffer,
        LoadPetInventory,
        LoadBotInventory,
        LoadBadgeInventory,
        LoadItemsInventory,
        SetActivatedBadges,
        EnableInventoryEffect,
        EffectEnable,
        RoomGetInfo,
        RoomUserAction,
        RoomDelete,
        RoomEventUpdate,
        RoomGetSettingsInfo,
        RoomSaveSettings,
        RoomSettingsMuteAll,
        RoomSettingsMuteUser,
        RoomLoadByDoorbell,
        DoorbellAnswer,
        RoomGetFilter,
        RoomAlterFilter,
        GetRoomBannedUsers,
        GetRoomRightsList,
        RoomRemoveAllRights,
        RoomRemoveUserRights,
        GetFloorPlanFurniture,
        GetFloorPlanDoor,
        SaveFloorPlanEditor,
        SaveRoomThumbnail,
        SetInvitationsPreference,
        SubmitRoomToCompetition,
        VoteForRoom,
        UserWalk,
        UserDance,
        UserSign,
        RoomBanUser,
        RoomUnbanUser,
        RoomKickUser,
        RateRoom,
        DropHanditem,
        GiveHanditem,
        GiveRespect,
        GiveRights,
        StartTyping,
        StopTyping,
        IgnoreUser,
        UnignoreUser,
        LookAtUser,
        TradeAccept,
        TradeAddItemOffer,
        TradeCancel,
        TradeConfirm,
        TradeDiscard,
        TradeRemoveItem,
        TradeStart,
        TradeUnaccept,
        SetChatPreference,
        ToggleSitting,
        RoomAddFloorItem,
        PlaceBuildersWallItem,
        FloorItemMove,
        WallItemMove,
        TriggerDiceClose,
        TriggerDiceRoll,
        TriggerItem,
        TriggerMoodlight,
        TriggerWallItem,
        EnterOneWayDoor,
        UpdateMoodlight,
        OpenPostIt,
        RoomAddPostIt,
        SavePostIt,
        UseHabboWheel,
        ActivateMoodlight,
        RoomApplySpace,
        SaveFootballGateOutfit,
        YouTubeChoosePlaylistVideo,
        YouTubeGetPlayer,
        YouTubeGetPlaylistGet,
        TileStackMagicSetHeight,
        SaveRoomBackgroundToner,
        SaveRoomBranding,
        MannequinSaveData,
        MannequinUpdateData,
        LoadJukeboxDiscs,
        JukeboxAddPlaylistItem,
        JukeboxRemoveSong,
        GetJukeboxPlaylists,
        GetMusicData,
        OpenGift,
        ReedemExchangeItem,
        RemovePostIt,
        ConfirmLoveLock,
        UsePurchasableClothing,
        WiredSaveCondition,
        WiredSaveEffect,
        WiredSaveMatching,
        WiredSaveTrigger,
        BotActions,
        BotSpeechList,
        PlaceBot,
        PlacePet,
        MovePet,
        PickUpBot,
        PickUpItem,
        PickUpPet,
        HorseAddSaddle,
        HorseAllowAllRide,
        HorseMountOn,
        HorseRemoveSaddle,
        GetPetTrainerPanel,
        PetGetInformation,
        RespectPet,
        PetBreedResult,
        PetBreedCancel,
        CompostMonsterplant,
        ModerationToolUserTool,
        ModerationToolRoomChatlog,
        ModerationToolRoomTool,
        ModerationBanUser,
        ModerationKickUser,
        ModerationMuteUser,
        ModerationLockTrade,
        ModerationToolCloseIssue,
        ModerationToolGetRoomVisits,
        ModerationToolPerformRoomAction,
        ModerationToolPickIssue,
        ModerationToolReleaseIssue,
        ModerationToolSendRoomAlert,
        ModerationToolSendUserAlert,
        ModerationToolSendUserCaution,
        ModerationToolUserChatlog,
        ModerationToolIssueChatlog,
        ModerationToolIssueChatlogRefresh,
        AmbassadorAlert,
        GetUCPanel,
        GetUCPanelHotel,
        DeleteHelpTicket,
        SubmitHelpTicket,
        OpenBullyReporting,
        SendBullyReport,
        OpenHelpTool,
        OnGuideSessionDetached,
        GetHelperToolConfiguration,
        OnGuide,
        GuideToolMessageNew,
        GuideInviteToRoom,
        VisitRoomGuides,
        GuideEndSession,
        CancellInviteGuide,
        OpenQuests,
        LoadNextQuest,
        QuestCancel,
        QuestSeasonalStart,
        QuestStart,
        OpenAchievementsBox,
        CompleteSafetyQuiz,
        ConsoleInstantChat,
        ConsoleInviteFriends,
        FollowFriend,
        FriendListUpdate,
        FriendRequestListLoad,
        DeleteFriend,
        GetMyFriends,
        FindMoreFriends,
        GetGroupForums,
        GetGroupForumData,
        GetGroupForumThreadRoot,
        UpdateThread,
        UpdateForumSettings,
        AlterForumThreadState,
        PublishForumThread,
        ReadForumThread,
        RequestLeaveGroup,
        ConfirmLeaveGroup,
        AcceptGroupRequest,
        CreateGuild,
        GetGroupFurniture,
        GetGroupInfo,
        GetGroupMembers,
        GetGroupPurchaseBox,
        GetGroupPurchasingInfo,
        GroupDeclineMembershipRequest,
        GroupMakeAdministrator,
        GroupManage,
        GroupUpdateBadge,
        GroupUpdateColours,
        GroupUpdateName,
        GroupUpdateSettings,
        GroupUserJoin,
        SetFavoriteGroup,
        RemoveFavouriteGroup,
        RemoveGroupAdmin,
        DeleteGroup,
        GameCenterLoadGame,
        GameCenterJoinQueue,
        ClickGames,
        AcceptPoll,
        RefusePoll,
        AnswerPollQuestion,
        RetrieveCitizenshipStatus,
        NuxAcceptGifts,
        NuxReceiveGifts,
        HabboCamera,
        HabboCameraPublishPhoto,
        GetCameraRequest,
        GetCameraPrice,
        BullyRequestAccept,
        BullyRequestVote,
        BullyRequestNoVote,

        // Handshake
        ReleaseVersion,
        InitCrypto,
        GenerateSecretKey,
        SwfData,
        UniqueId,
        SsoTicket,
        InfoRetrieve,
        Pong,

        // Advertisement
        GetInterstitial,
        
        // Catalog
        GetBundleDiscountRuleset,
        GetCatalogIndex,
        GetCatalogPage,
        PurchaseFromCatalog,
        PurchaseFromCatalogAsGift,
        BuildersClubFurniCount,

        // Competition
        GetCurrentTimingCode,
        RoomCompetitionInit,

        // Friendlist
        MessengerInit,
        GetFriendRequests,
        HabboSearch,
        RequestFriend,
        DeclineFriend,
        AcceptFriend,
        SendMsg,

        // Inventory.Badges
        GetBadgePointLimits,

        // Inventory.Purse
        GetCreditsInfo,

        // Navigator
        GetUserFlatCats,
        GetGuestRoom,
        MyRoomsSearch, // AIR SPECIFIC
        MyFavouriteRoomsSearch, // AIR SPECIFIC
        MyRoomHistorySearch, // AIR SPECIFIC
        PopularRoomsSearch, // AIR SPECIFIC
        RoomsWithHighestScoreSearch, // AIR SPECIFIC
        RoomAdSearch, // AIR SPECIFIC
        GetOfficialRooms, // AIR SPECIFIC
        AddFavouriteRoom,
        DeleteFavouriteRoom,
        UpdateHomeRoom,
        
        // RoomSettings
        GetRoomSettings,
        SaveRoomSettings,

        // Room.Chat
        TypingStart,
        TypingStop,
        Chat,
        Shout,
        Whisper,

        // Room.Engine
        GetRoomEntryData,
        GetFurnitureAliases,
        MoveAvatar,

        // Room.Session
        OpenFlatConnection,

        // Users
        GetExtendedProfile,
        GetSelectedBadges,
        GetRelationshipStatusInfo,
        ScrGetUserInfo,
        GetIgnoredUsers,

        // Tracking
        LatencyPingRequest,
        LatencyPingReport,
        EventLog
    }
}
